### ISSUE TITLE
cannot satisfy package ghc-prim when building ghc

### ISSUE THREAD

**Issue by depsterr** [dilyn-corner/KISS-haskell#2]
After building and installing ghc-bootstrap ghc fails, seemingly because it is "unable to satisfy package ghc-prim"

[build log pastebin](https://pastebin.com/MMn7meXU)

**Comment by dilyn-corner** [comment]
Hm. I can't reproduce this (I get a linker error at the step after this - that's something to troubleshoot!) and when I initially bumped the versions I was able to successfully build everything (I haven't attempted to use this in quite some time). 
I feel like I got this error when I first started this repo. What shell are you using? 

Aa an aside, are you intentionally installing `ghc-bootstrap` to `/usr/local`?

**Comment by depsterr** [comment]
I am using ash (the busybox sh shell), also no I did not, that was how it installed itself, I also found that a bit odd

**Comment by depsterr** [comment]
I noticed ghc was installed in both /usr/bin and /usr/local/bin, I then proceeded to remove the files in /usr/local/bin, install bash and run the install in bash (though kiss probably still uses sh -> ash), it now got past where it previously crashed. I will return once the build has finished / crashed to update.

**Comment by depsterr** [comment]
The build now succeeded, however, before I close the issues, perhaps it should be looked into if the ghc-bootstrap installs the binaries in /usr/local/bin and if it should require bash as a make dependency. Though I suspect bash was not needed.

**Comment by depsterr** [comment]
Upon retrying this in a virtual machine it all worked. I must have screwed up something on my machine as it works fine. Sorry for the inconvenience!

**Comment by dilyn-corner** [comment]
If I'm right and I've had this problem before, then that means this problem is a strange one (I installed the bootstrap multiple times yesterday and didn't see this). I'll try to see if there's any reason on the package's side why this may happen. 

Glad you've got it working now!
